spring:
  application:
    name: kafka-telemetry-data-consumer
  kafka.properties.spring.json.use.type.headers: false
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:29092"
        bindings:
          processTelemetryData-in-0:
            consumer:
              configuration:
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value.deserializer: de.codecentric.samples.kafkasamplesconsumer.serdes.TelemetryDataDeserializer
      bindings:
        processTelemetryData-in-0:
          consumer:
            useNativeEncoding: true
          group: ${spring.application.name}
          destination: space-probe-aggregate-telemetry-data
