spring:
  application:
    name: kafka-telemetry-data-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
        bindings:
          processTelemetryData-in-0:
            consumer:
              configuration:
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bindings:
        processTelemetryData-in-0:
          consumer:
            useNativeEncoding: true
          destination: space-probe-aggregate-telemetry-data
