version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    links:
     - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "nasa-space-probe-telemetry-data:3:1, space-probe-aggregate-telemetry-data:3:1"
    ports:
      - 9092:9092
  akhq:
    image: tchiotludo/akhq
    depends_on:
      - kafka
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            wurstmeister-kafka:
              properties:
                bootstrap.servers: "localhost:9092"
                default.api.timeout.ms: "60000"
    ports:
      - "9080:8080"
